-- 프로그래머스 - join예제
-- 곱셈, 정렬조건 유의

-- 코드를 입력하세요
SELECT A.PRODUCT_CODE, SUM(A.PRICE * B.SALES_AMOUNT) AS SALES
FROM OFFLINE_SALE AS B 
JOIN PRODUCT AS A
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY B.PRODUCT_ID
ORDER BY SALES DESC, A.PRODUCT_CODE ASC