-- 프로그래머스 groupby 예제
-- in과 리스트 활용

-- 코드를 입력하세요
SELECT A.CATEGORY, A.MAX_PRICE, B.PRODUCT_NAME
FROM FOOD_PRODUCT AS B 
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
) AS A ON B.PRICE = A.MAX_PRICE AND A.CATEGORY = B.CATEGORY
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC